# Generated by Django 3.2 on 2022-01-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
