# Generated by Django 3.2 on 2022-01-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='height',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
