# Generated by Django 3.2 on 2022-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20220107_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
