# Generated by Django 3.0.5 on 2022-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_info_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('height', models.CharField(default=None, max_length=100)),
                ('age', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
