# Generated by Django 3.2 on 2022-01-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_information_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='age',
        ),
        migrations.RemoveField(
            model_name='information',
            name='height',
        ),
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.AddField(
            model_name='information',
            name='company_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='company_profile',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AddField(
            model_name='information',
            name='detail_url',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='information',
            name='exp_requirements',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='job_requirements',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='information',
            name='p_tag',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='information',
            name='place',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='post_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='salary',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='target_post',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='weal',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
